### PR TITLE
Fix 2FA

### PR DESCRIPTION
**Pull request by CodeWithBryan**
Solves #10 

Sorry, original PR was off master and I had some other changes in it that I had added. Here's just the fix.

### CODE REVIEW

**Comment by matias-kovero** [comment]
Hi @bryandesigning 
are you sure this fixes the issue?
As I tested already:
```javascript
let body =  {
  email: email,
  hwCode: hwid,
  activateCode: code,
};
```
and it still gave `211 - Wrong activation code`

**Comment by bryandesigning** [comment]
This is what is working for me, as well as a few other repo's I looked at
that have similar API wrappers for tarkov.

**Comment by CodeWithBryan** [comment]
This is what works for me, as well as a few other repo's of Tarkov API wrappers in various languages. They all use hwCode

**Comment by matias-kovero** [comment]
> This is what works for me, as well as a few other repo's of Tarkov API wrappers in various languages. They all use hwCode

Yeah I know, this api uses also hwCode. Just changed it for 1 push to device_id as people were telling it's the right one. Got this fixed now on my version also, as I saw a major typo.

You have the typo also fixed on this version.

**Pull request merged**
